### ISSUE TITLE
Transparency not preserved after first frame

### ISSUE THREAD

**Issue by zamponotiropita** [hidefromkgb/gif_load#5]
First, thanks for the awesome work.

I noticed that the transparency is not preserved after the first frame on certain gifs.
In the example below the transparent layer disappears after the first frame.

![](https://user-images.githubusercontent.com/23146389/48676492-ae178e80-eb5f-11e8-8b20-645fa2863b97.gif)

this ones transparency is even more problematic:

![](https://user-images.githubusercontent.com/23146389/48708110-84ab4100-ebf9-11e8-858f-692d32147388.gif)

Thanks for the help in advance.

**Comment by hidefromkgb** [comment]
Okay, I see. When the decoder encounters a non-black transparency mark it doesn`t set all of the channels to 0, only the alpha.
Fixed for the C example in c762113.

**Comment by hidefromkgb** [comment]
Oh well. Shall fix it in the Python version soon.

**Comment by hidefromkgb** [comment]
Fixed.

Both Python and C shall return correct results now.

**Comment by zamponotiropita** [comment]
Works like charm. Thanks for the support!

**Comment by hidefromkgb** [comment]
OK. Closing as fixed.
