### ISSUE TITLE
Previous frames wrongly preserved

### ISSUE THREAD

**Issue by zamponotiropita** [hidefromkgb/gif_load#6]
Hello,

In the example below previous frames are wrongly preserved in subsequent frames:

![zu4r](https://user-images.githubusercontent.com/23146389/49153438-a600e100-f30d-11e8-86c8-0c892cbf3f80.gif)

=>

![spritesheet](https://user-images.githubusercontent.com/23146389/49153528-e06a7e00-f30d-11e8-9691-49d9fdb1b822.png)

I tested it in the python version.
Thanks for looking into it.

**Comment by Eagl61** [comment]
Please, tell me, how can i get a picture/frame and display it on the screen, for example using WinAPI?

**Comment by hidefromkgb** [comment]
@Eagl61 Please file a new ticket, since in this one your question is off-topic.

**Comment by hidefromkgb** [comment]
@zamponotiropita, investigating.
Damn, I remember having tested both frontends on the GIFLIB example suite, why does this keeps happening? T__T

**Comment by hidefromkgb** [comment]
A-ha. So finally I\`ve found it — a GIF that uses `GIF_PREV` as its main blending mode. First time in 2++ years!
Thank you @zamponotiropita for this sample. Fixing.

**Comment by hidefromkgb** [comment]
Fixed in 394d79a5, please verify.

**Comment by hidefromkgb** [comment]
![m5np](https://user-images.githubusercontent.com/3729964/49332795-e4b7c500-f5b3-11e8-946a-476354ab7381.gif)
Just in case: another `GIF_PREV` image, taken [from here](http://www.theimage.com/animation/pages/disposal2.html).

**Comment by hidefromkgb** [comment]
…ping?

**Comment by zamponotiropita** [comment]
@hidefromkgb thanks for the update! I was away from keyboard the recent dates. Checking it right now

**Comment by zamponotiropita** [comment]
@hidefromkgb works like a charm, tested with python

**Comment by hidefromkgb** [comment]
Yay!
Closing as fixed.
