### ISSUE TITLE
Static code analyzer warning

### ISSUE THREAD

**Issue by wcout** [hidefromkgb/gif_load#8]
I've probed the clang analyzer on the code and it gives one warning. As the code is .. hm .. complex .. I can't judge if this is a valid one, so I simply show it here:

[report.zip](https://github.com/hidefromkgb/gif_load/files/2729258/report.zip)

**Comment by hidefromkgb** [comment]
Seems like I broke the Clang analyzer! Yay…
1. [50] cannot be false right away, as `ctbl` equals at least 4 (and at most 256) at the start, see line 102.
1. `code` gets initialized with exactly `ctbl` zero values, starting at the address of `code[0]`, and then gets appended 1 element each SP/MP iteration, until either its size equals `GIF_CLEN` or it gets invalidated, see line 118.
1. `prev` never exceeds `ctbl` between lines 109 and 130, as `prev` equals 0 at the start and then gets its value from `curr` at each iteration, whereas `curr` exceeding `ctbl` terminates the function with the return value of –5 (see line 141), before `prev` ever gets a chance to become greater than `ctbl`.
1. when `ctbl` reaches `GIF_CLEN` and thus cannot expand further, its corresponding `mask` prevents `curr` from becoming greater than `GIF_CLEN – 1`.

Maybe it\`s worth filing a bug to Clang analyzer…

**Comment by hidefromkgb** [comment]
Seems like I broke the Clang analyzer! Yay…
1. [50] cannot be false right away, as `ctbl` equals at least 4 (and at most 256) at the start, see line 102.
1. `code` gets initialized with exactly `ctbl` zero values, starting at the address of `code[0]`, and then gets appended 1 element each SP/MP iteration, until either its size (and the value of `ctbl` which drives that process) equals `GIF_CLEN` or it gets invalidated, see line 118.
1. `prev` never exceeds `ctbl` between lines 109 and 130, as `prev` equals 0 at the start and then gets its value from `curr` at each iteration, whereas `curr` exceeding `ctbl` terminates the function with the return value of –5 (see line 141), before `prev` ever gets a chance to become greater than `ctbl`.
1. when `ctbl` reaches `GIF_CLEN` and thus cannot further expand `code`, its corresponding `mask` prevents `curr` from becoming greater than `GIF_CLEN – 1`, see line 118.

Maybe it\`s worth filing a bug to Clang analyzer…

**Comment by hidefromkgb** [comment]
If it does, please also apply the analyzer to the latest commit, 0ed5be0a2de7146dde6b0b7cb647ee8309aa86f5.

**Comment by hidefromkgb** [comment]
If it does, please also apply the analyzer to the latest commit, 0ed5be0a2de7146dde6b0b7cb647ee8309aa86f5, and see if it finds anything.

**Comment by hidefromkgb** [comment]
Well, OK. Does it also complain if the loop goes as follows?

        for (curr = ++ctbl; curr; )
            code[--curr] = 0;

**Comment by wcout** [comment]
Yes

**Comment by hidefromkgb** [comment]
Please show me the report.

**Comment by wcout** [comment]
[report2.zip](https://github.com/hidefromkgb/gif_load/files/2730260/report2.zip)

**Comment by hidefromkgb** [comment]
Well, now that does seem like a bug in the analyzer.
The loop condition is now obviously true.

**Comment by hidefromkgb** [comment]
May I close this ticket?

**Comment by wcout** [comment]
Yes please.

Your analysis seems profound, so it is really most probably a clang analyzer issue.
(Though I hoped, that fixing the memory corruptions would make this warning go away too).
